### PR TITLE
Fix table overflow bug

### LINKED ISSUE #301: User Dashboard Name-limitation
This is what happen when a user has a long name.
image

----
Fix this by **only display max 12 characters** of first and last name. Longer name will be 
```12CharacterOfFirst... 12CharacterOfLast...```

The code is located in src/pages/overview/OverviewProfile.js at [line 19](https://github.com/SCE-Development/Core-v4/blob/7a9a047c9537f698cad43ca013090922265bc863/src/Pages/Overview/OverviewProfile.js#L19)

### PR DESCRIPTION
**Pull request by aashrav**
Resolves #301

### CODE REVIEW

File: src/Pages/Overview/OverviewProfile.js [hunk 1]
```diff
@@ -17,11 +17,13 @@ export default function OverviewProfile (props) {
   return (
     <tr>
       <td>
-        {props.user.firstName[0].toUpperCase() +
-          props.user.firstName.slice(1, props.user.firstName.length) +
-          ' ' +
-          props.user.lastName[0].toUpperCase() +
-          props.user.lastName.slice(1, props.user.lastName.length)}
+        <div className='name'>
+          {props.user.firstName[0].toUpperCase() +
```
Comment (evanugarte) [inline src/Pages/Overview/OverviewProfile.js]: can you move this to a function in [`src/APIFunctions/Profile.js`](https://github.com/SCE-Development/Core-v4/blob/dev/src/APIFunctions)?

I ask because the same logic for first and last name is done [here in `src/Pages/Profile/MemberView/Profile.jsx`](https://github.com/SCE-Development/Core-v4/blob/05287caeb4f09ad7487212ea6f529261364c5a87/src/Pages/Profile/MemberView/Profile.jsx#L25) too. 

You can define a funciton in the file like this

```js
export function formatFirstAndLastName(user) {
  return user.firstName[0].toUpperCase() +
            user.firstName.slice(1, user.firstName.length) +
            ' ' +
            user.lastName[0].toUpperCase() +
            user.lastName.slice(1, user.lastName.length)
```

Now, you can call on this helper by importing it at the top and the line here becomes
```jsx
{formatFirstAndLastName(props.user)}
```

Comment (aashrav) [reply src/Pages/Overview/OverviewProfile.js]: The function that you defined doesn't actually format the first and last name, so should I call it getFirstAndLastName() instead?

Comment (evanugarte) [reply src/Pages/Overview/OverviewProfile.js]: You would send in a parameter `user`, which your function does the work of capitalizing the first letters of the name.

File: src/Pages/Overview/OverviewProfile.js [hunk 2]
```diff
@@ -17,11 +18,7 @@ export default function OverviewProfile (props) {
   return (
     <tr>
       <td>
-        {props.user.firstName[0].toUpperCase() +
-          props.user.firstName.slice(1, props.user.firstName.length) +
-          ' ' +
-          props.user.lastName[0].toUpperCase() +
-          props.user.lastName.slice(1, props.user.lastName.length)}
+        <div className='name'>{formatFirstAndLastName(props.user)}</div>
```
Comment (evanugarte) [inline src/Pages/Overview/OverviewProfile.js]: Awesome! Can you also replace the [code here](https://github.com/SCE-Development/Core-v4/blob/05287caeb4f09ad7487212ea6f529261364c5a87/src/Pages/Profile/MemberView/Profile.jsx#L25) with your new function call?

**Comment by ThaiQ** [comment]
Travis is failing, check your test cases

File: src/Pages/Overview/OverviewProfile.js [hunk 3]
```diff
@@ -17,11 +17,13 @@ export default function OverviewProfile (props) {
   return (
     <tr>
       <td>
```
[the remark this answers is not in the document]
Comment (aashrav) [reply src/Pages/Overview/OverviewProfile.js]: i need the div...when I tried to format the inside the <td> tag it didnt' work

File: src/Pages/Overview/Overview.css [hunk 4]
```diff
@@ -1,7 +1,12 @@
 .App {
```
[the remark this answers is not in the document]
Comment (aashrav) [reply src/Pages/Overview/Overview.css]: can I delete .App, .App-header, .App-link. That is the default code that come in the css file. I don't believe we are using them(isn't any change when I comment it out).

[the remark this answers is not in the document]
Comment (aashrav) [reply src/Pages/Overview/Overview.css]: overview.css keeps changing back to uppercase and results in bugs

File: src/APIFunctions/Profile.js [hunk 5]
```diff
@@ -47,3 +47,13 @@ export async function setEmailToVerified (email) {
     })
   return emailSetToVerified
 }
+
```
Comment (evanugarte) [inline src/APIFunctions/Profile.js]: Add a simple comment like the other functions in this code explaining what the function does with parameters and return types
