### PR TITLE
Fixes Parameters in ErrorLog

### LINKED ISSUE #424: Refactor addErrorLog Parameter Types
lets change the parameters in [`api/util/errorLog-function.js`](https://github.com/SCE-Development/Core-v4/blob/dev/api/util/errorLog-function.js).

change
```js
async function addErrorLog(req){
```
to
```js
async function addErrorLog(userEmail, errorTime, apiEndpoint, errorDescription){
```

### PR DESCRIPTION
**Pull request by seemavora**
Resolves #424

### CODE REVIEW

File: api/util/errorLog-function.js [hunk 1]
```diff
@@ -9,13 +9,13 @@ const ErrorLog = require('../models/ErrorLog');
...
  */
-async function addErrorLog(req){
+async function addErrorLog(userEmail, errorTime, apiEndpoint, errorDescription){
   let errorSaved = true;
   const newError = new ErrorLog({
-    userEmail: req.body.userEmail,
-    errorTime: req.body.errorTime,
-    apiEndpoint: req.body.apiEndpoint,
-    errorDescription: req.body.errorDescription
+    userEmail: userEmail,
```
Comment (evanugarte) [inline api/util/errorLog-function.js:15]: fun fact, in javascript doing 
```suggestion
    userEmail,
```
implies
```js
userEmail: userEmail
```

when the left and right side have the same name. Change all of them to the suggested format

File: api/util/errorLog-function.js [hunk 2]
```diff
@@ -9,13 +9,13 @@ const ErrorLog = require('../models/ErrorLog');
  * @param {string} req.body.apiEndpoint - The location of the error
  * @param {string} req.body.errordescription - The description of the error
  */
-async function addErrorLog(req){
+async function addErrorLog(userEmail, errorTime, apiEndpoint, errorDescription){
```
Comment (evanugarte) [inline api/util/errorLog-function.js:12]: rename the **file** to `ErrorLog.js`

Comment (seemavora) [reply api/util/errorLog-function.js:12]: going to rename it errorLog.js because that is the format for the other files in the folder
