### PR TITLE
Fix bcryptjs Functionality

### LINKED ISSUE #354: New bcryptjs Dependency Blocks Login
Since #340, the new `bcryptjs` has not been functioning the same way as our old bcrypt depencency. It has to do with saving the user to our database where the password field is empty.

### PR DESCRIPTION
**Pull request by evanugarte**
Resolves #354. Also fixed bug regarding token generation where only the
user's first name is returned with token information.

### CODE REVIEW

File: api/routes/user.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ router.post('/register', function (req, res) {
       return res.status(BAD_REQUEST).send({ message: testPassword.message })
     }
 
-    newUser.save(function (error) {
+    newUser.save(function (error, result) {
```
Comment (jerrylee17) [inline api/routes/user.js]: result isn't used though....?

Comment (evanugarte) [reply api/routes/user.js]: Thanks, it is now removed.
