### PR TITLE
remove redundant checkIfEmailExists on user registration, fix user registration endpoint url

### LINKED ISSUE #1459: Remove unauthenicated api to check if an email is registered
- [ ] remove all code related to `/checkIfUserExists`

https://github.com/SCE-Development/Clark/blob/053254e98c69909dd5e834cbb17fc4592a9c63fb/api/main_endpoints/routes/User.js#L72

- [x] make the refactor to this function, specifically is if/else
https://github.com/SCE-Development/Clark/blob/053254e98c69909dd5e834cbb17fc4592a9c63fb/api/main_endpoints/routes/Auth.js#L35
- [ ] with that removed, run these test steps:

1. ensure creating an account on the website works, on the sign up page
1. ensure creating a second account with the same email, says "this email exists already" when we try to submit

### PR DESCRIPTION
**Pull request by knhn1004**
resolves #1459

### CODE REVIEW

File: src/APIFunctions/Auth.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ export async function registerUser(userToRegister) {
     numberOfSemestersToSignUpFor,
     captchaToken
   } = userToRegister;
-  const url = new URL('/Auth/register', BASE_API_URL);
+  const url = new URL('/api/Auth/register', BASE_API_URL);
```
Comment (knhn1004) [inline src/APIFunctions/Auth.js:32]: yeah, I forgot to add it last time :(

File: api/main_endpoints/util/userHelpers.js [hunk 2]
```diff
@@ -118,9 +117,13 @@ async function registerUser(userToAdd) {
...
     await newUser.save()
-      .catch(_ => {
+      .catch(e => {
         result.userSaved = false;
-        result.message = 'Username already exists.';
+        if (e.code === 11000) {
+          result.message = 'Username already exists.';
+        } else {
+          result.message = 'Failed creating account.';
+        }
```
Comment (evanugarte) [inline api/main_endpoints/util/userHelpers.js]: can we also use `logger.error` to log whatever the error is
```suggestion
        result.message = 'Failed creating account.';
        if (e.code === 11000) {
          result.message = 'Username already exists.';
        }
```

**Review by gridenjoyer6 — APPROVED** [review]

**Review by evanugarte — APPROVED** [review]

**Review by weslayer — APPROVED** [review]
lgtm
