### PR TITLE
send PDFs to backend in chunks

### LINKED ISSUE #1687: send PDFs to backend in chunks
PDFs are currently sent to the server for printing in whole; trying to send large PDFs will fail
ex: 200 mb PDF causing a failure
Image

we can get around this by breaking the PDF into smaller chunks and sending those chunks one at a time to the server for reassembly

### PR DESCRIPTION
**Pull request by thebeninator**
resolves #1687

todo: 
- [x]  prometheus metric for printing folder size 
- [x] prometheus metric for total expired chunks deleted
- [x] prometheus metric from total expired bytes deleted

### CODE REVIEW

File: api/main_endpoints/routes/Printer.js [hunk 1]
```diff
@@ -40,6 +41,14 @@ const storage = multer.diskStorage({
 
 const upload = multer({ storage });
 
+const CHUNK_MIN_EXPIRY = 300000; // 5 minutes
```
Comment (thebeninator) [inline api/main_endpoints/routes/Printer.js]:
```suggestion
const FIVE_MINUTES_MS  = 300000; // 5 minutes
```

File: api/main_endpoints/routes/Printer.js [hunk 2]
```diff
@@ -74,31 +83,74 @@ router.post('/sendPrintRequest', upload.single('file'), async (req, res) => {
...
+    }
+
+    const stream = await fs.createReadStream(pdf);
+    const data = new FormData();
+    data.append('file', stream, {filename: id, type: 'application/pdf'});
+    data.append('copies', copies);
+    data.append('sides', sides);
+
+    try {
+      // full pdf can be sent to quasar no problem
```
Comment (thebeninator) [inline api/main_endpoints/routes/Printer.js]: lets limit the file size from the frontend to 150mb

the limit should be checked in the frontend as well as in the api code, maybe content length header?

File: api/main_endpoints/routes/Printer.js [hunk 3]
```diff
@@ -74,31 +83,74 @@ router.post('/sendPrintRequest', upload.single('file'), async (req, res) => {
...
-    data,
-    {
-      headers: {
-        ...data.getHeaders(),
+
+  const dir = path.join(__dirname, 'printing');
+  const { totalChunks, chunkIdx } = req.body;
+
+  // reassemble pdf on last chunk received
+  if (Number(chunkIdx) === totalChunks - 1) {
```
Comment (thebeninator) [inline api/main_endpoints/routes/Printer.js]: lets do

```js
if (Number(chunkIdx) <= totalChunks - 1) {
  return res.sendStatus(OK)
}
```

then under the if statement it can be all the code to reassemble the pdf

File: api/main_endpoints/routes/Printer.js [hunk 4]
```diff
@@ -74,31 +83,74 @@ router.post('/sendPrintRequest', upload.single('file'), async (req, res) => {
...
       res.sendStatus(SERVER_ERROR);
-    });
+    }
+
+  } else {
+    res.sendStatus(OK);
+  }
+});
+
+router.post('/forceCleanUpChunks', express.json(), async (req, res) => {
```
Comment (thebeninator) [inline api/main_endpoints/routes/Printer.js]: token for this would be good

File: api/main_endpoints/routes/Printer.js [hunk 5]
```diff
@@ -74,31 +83,74 @@ router.post('/sendPrintRequest', upload.single('file'), async (req, res) => {
...
+  }
+
+  const id = req.body.id;
+  const dir = path.join(__dirname, 'printing');
+  await cleanUpChunks(dir, id);
+});
+
+router.get('/metrics', async (req, res) => {
+  res.setHeader('Content-Type', register.contentType);
+  res.end(await register.metrics());
```
Comment (thebeninator) [inline api/main_endpoints/routes/Printer.js]: lets remove before we merge

File: api/main_endpoints/util/Printer.js [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+
+    for (let chunk of chunks) {
+      if (!path.basename(chunk).includes(id)) continue;
+
+      await fs.promises.unlink(path.join(dir, chunk), err => {
+        logger.error(`Failed to delete chunk with id ${id} in ${dir}: ` + err);
+      });
+    }
+  } catch (_) {
+    return false;
```
Comment (thebeninator) [inline api/main_endpoints/util/Printer.js]: lets add logger her and log the error before returning false

File: api/main_endpoints/util/Printer.js [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+ * Deletes all chunks of specified age or older, 'expired', from a directory
+ * @param {String} dir The directory the chunks are stored in
+ * @param {Number} expiry Minimum age (ms) to be considered expired
+ */
+async function cleanUpExpiredChunks(dir, expiry) {
+  try {
+    const chunks = await fs.promises.readdir(dir);
+
+    for (let chunk of chunks) {
+      if (!path.extname(chunk).includes('.pdf')
```
Comment (thebeninator) [inline api/main_endpoints/util/Printer.js]: might read better
```js
if (!['.pdf', '.CHUNK'].includes(path.extname(chunk)))
```

File: api/main_endpoints/util/Printer.js [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+      const age = Date.now() - stats.mtimeMs;
+
+      if (age >= expiry) {
+        await fs.promises.unlink(path.join(dir, chunk), err => {
+          logger.warn(`Failed to delete expired chunk in ${dir}: ` + err);
+        });
+      }
+    }
+  } catch (_) {
+    return false;
```
Comment (thebeninator) [inline api/main_endpoints/util/Printer.js]: log moment

File: api/util/metrics.js [hunk 9]
```diff
@@ -25,33 +25,38 @@ class MetricsHandler {
...
+  totalChatMessagesPerChatRoom = new client.Counter({
+    name: 'total_chat_messages_per_chatroom',
+    help: 'Total number of messages sent per chatroom',
+    labelNames: ['id']
+  });
+
+  currentSizeOfPrintingFolder = new client.Gauge({
+    name: 'current_size_of_printing_folder',
+    help: 'Current size of printing folder'
+  });
```
Comment (thebeninator) [inline api/util/metrics.js]: add the unit of measure to this, like bytes if its bytes. does fs return IEC bytes? if so, add the exact unit used in the help message, helps a lot
```suggestion
  currentSizeOfPrintingFolderBytess = new client.Gauge({
    name: 'current_size_of_printing_folder_bytes',
    help: 'Current size of printing folder'
  });0
```

File: src/APIFunctions/2DPrinting.js [hunk 10]
```diff
@@ -80,21 +80,46 @@ export function parseRange(pages, maxPages) {
...
+      const res = await fetch(url.href, {
+        method: 'POST',
+        headers: {
+          'Authorization': `Bearer ${token}`
+        },
+        body: chunkData
+      });
+      if (res.ok) {
+        status.responseData = true;
+      }
```
Comment (thebeninator) [inline src/APIFunctions/2DPrinting.js]:
```suggestion
      status.responseData = !!res.ok;
```

File: src/Pages/2DPrinting/2DPrinting.js [hunk 11]
```diff
@@ -49,6 +51,26 @@ export default function Printing(props) {
...
+      keepalive: true
+    });
+  }
+
+  useEffect(() => {
+    window.addEventListener('beforeunload', cleanUpChunks);
+    return () => {
+      window.removeEventListener('beforeunload', cleanUpChunks);
+    };
+  });
```
Comment (thebeninator) [inline src/Pages/2DPrinting/2DPrinting.js]: i dont think this should be on the user's browser to manage the servers state.

do we need this? if anything we can add calling the clean up endpoint from a dedicated webpage in the next pr

File: api/main_endpoints/routes/Printer.js [hunk 12]
```diff
@@ -40,6 +41,14 @@ const storage = multer.diskStorage({
 
 const upload = multer({ storage });
 
+const FIVE_MINUTES_MS = 300000;
+
+setInterval(() => {
+  const dir = path.join(__dirname, 'printing');
+  cleanUpExpiredChunks(dir, FIVE_MINUTES_MS);
+  recordPrintingFolderSize(dir);
+}, FIVE_MINUTES_MS);
```
Comment (evanugarte) [inline api/main_endpoints/routes/Printer.js]: maybe this should only run if printing is enabled in the config file?

```js
if (PRINTING.ENABLED) {
  setInterval(/* ... */);
}

```

File: api/main_endpoints/routes/Printer.js [hunk 13]
```diff
@@ -74,31 +83,78 @@ router.post('/sendPrintRequest', upload.single('file'), async (req, res) => {
...
+
+  // reassemble pdf on last chunk received
+  if (Number(chunkIdx) < totalChunks - 1) {
+    return res.sendStatus(OK);
+  }
+
+  const { copies, sides, id } = req.body;
+
+  const chunks = await fs.promises.readdir(dir);
+  const pdf = path.join(dir, id + '.pdf');
```
Comment (evanugarte) [inline api/main_endpoints/routes/Printer.js]:
```suggestion
  const assembledPdfFromChunks = path.join(dir, id + '.pdf');
```

File: api/main_endpoints/routes/Printer.js [hunk 14]
```diff
@@ -74,31 +83,78 @@ router.post('/sendPrintRequest', upload.single('file'), async (req, res) => {
...
+    return res.sendStatus(UNAUTHORIZED);
+  }
+
+  if (!PRINTING.ENABLED) {
+    logger.warn('Printing is disabled, chunk cleanup will not commence');
+  }
+
+  const id = req.body.id;
+  const dir = path.join(__dirname, 'printing');
+  await cleanUpChunks(dir, id);
```
Comment (evanugarte) [inline api/main_endpoints/routes/Printer.js]: i think we need to do a res.sendStatus here

also lets respond to the user with a json object of the number of chunk files deleted, and total space saved in bytes

File: api/main_endpoints/util/Printer.js [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+    for (let chunk of chunks) {
+      if (!['.pdf', '.CHUNK'].includes(path.extname(chunk))) continue;
+
+      const stats = await fs.promises.stat(path.join(dir, chunk));
+      const age = Date.now() - stats.mtimeMs;
+
+      if (age >= expiry) {
+        await fs.promises.unlink(path.join(dir, chunk), err => {
+          logger.warn(`Failed to delete expired chunk in ${dir}: ` + err);
+        });
```
Comment (evanugarte) [inline api/main_endpoints/util/Printer.js:48]: lets add 2 more metrics here. will help us see if cleanup is happening from incomplete requests
- number of expired chunks deleted
- total expired bytes deleted

Comment (thebeninator) [reply api/main_endpoints/util/Printer.js:48]: done

File: api/main_endpoints/routes/Printer.js (hunk 14 above)
Comment (thebeninator) [reply api/main_endpoints/routes/Printer.js]: deleted endpoint

File: api/main_endpoints/routes/Printer.js (hunk 13 above)
Comment (thebeninator) [reply api/main_endpoints/routes/Printer.js]: done

File: api/main_endpoints/routes/Printer.js (hunk 12 above)
Comment (thebeninator) [reply api/main_endpoints/routes/Printer.js]: done

**Review by evanugarte — APPROVED** [review]

**Review by weslayer — APPROVED** [review]
beninated

**Review by n8thantran — APPROVED** [review]
epic
